server:
  port: 4100
  
spring:
   application:
    name: springcloud-clint-zipkin
   zipkin:
    base-url: http://localhost:4200

eureka:
  client:
    register-with-eureka: false
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-${server.port}
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: $project.name$
  company.name: www.sjz.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$    